# Generated by Django 5.0.7 on 2024-07-21 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
