# Generated by Django 5.0.7 on 2024-07-28 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_advertising'),
        ('users', '0006_clientpaid_sellerpaid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerpaid',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellerpaid',
            name='user',
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=150)),
                ('client_addres', models.TextField(default='')),
                ('paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('state', models.CharField(choices=[('confirm', 'در انتظار تایید فروشنده'), ('confirmed', 'تایید شد'), ('post', 'تحویل پست داده شد'), ('recived', 'تحویل داده شد')], max_length=150)),
                ('post_id', models.CharField(blank=True, max_length=250, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientPaid',
        ),
        migrations.DeleteModel(
            name='SellerPaid',
        ),
    ]
