# Generated by Django 5.0.7 on 2024-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_paid_user_cartpaided'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='total_count',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
