# Generated by Django 5.0.7 on 2024-07-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_paid_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
