# Generated by Django 5.0.7 on 2024-07-29 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_advertising'),
        ('users', '0010_paid_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed', models.CharField(choices=[('product', 'کالا معیوب بوده است'), ('post', 'کالا ارسال نشده است'), ('postId', 'بارکد نامعتبر است'), ('product_false', 'کالای اشتباه ارسال شده است')], max_length=150)),
                ('description', models.TextField(blank=True, default='Description', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_product', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
