# Generated by Django 5.0.7 on 2024-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_failedproduct_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failedproduct',
            old_name='client',
            new_name='clientId',
        ),
        migrations.RemoveField(
            model_name='failedproduct',
            name='failed',
        ),
        migrations.AddField(
            model_name='failedproduct',
            name='post',
            field=models.BooleanField(default=False, help_text='کالا ارسال نشده است'),
        ),
        migrations.AddField(
            model_name='failedproduct',
            name='postId',
            field=models.BooleanField(default=False, help_text='بارکد نامعتبر است'),
        ),
        migrations.AddField(
            model_name='failedproduct',
            name='product_error',
            field=models.BooleanField(default=False, help_text='کالا معیوب بوده است'),
        ),
        migrations.AddField(
            model_name='failedproduct',
            name='product_false',
            field=models.BooleanField(default=False, help_text='کالای اشتباه ارسال شده است'),
        ),
    ]
