# Generated by Django 5.0.7 on 2024-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_failedproduct_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedproduct',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
